services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft-vanilla
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "1.20.1"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "4G"
    volumes:
      - ./server:/data
    restart: unless-stopped 